services:
  # 1. BASE DE DATOS (PostgreSQL)
  task-db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    container_name: task-manager-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_internal_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # 2. BACKEND (Express.js)
  task-backend:
    build:
      context: ./backend
    container_name: task-manager-backend
    restart: unless-stopped
    depends_on:
      task-db:
        condition: service_healthy
    environment:
      # Apunta a 'task-db' de forma interna y automática
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@task-db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN:-15m}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      PORT: 3000
      NODE_ENV: production
      CLIENT_URL: ${CLIENT_URL}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    networks:
      - proxy_network       # Red para que Nginx Proxy Manager lo localice
      - task_internal_net   # Red privada para hablar con la base de datos

  # 3. FRONTEND (React + Vite)
  task-frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: task-manager-frontend
    restart: unless-stopped
    depends_on:
      - task-backend
    networks:
      - proxy_network       # Red para que Nginx Proxy Manager lo localice

networks:
  proxy_network:
    external: true          # Conecta con tu Nginx global de AWS
  task_internal_net:
    driver: bridge          # Red privada exclusiva para este proyecto

volumes:
  postgres_data:
