INSERT INTO "Task" (title, description, status, priority, "dueDate", "userId", "createdAt", "updatedAt")
VALUES
  ('Diseñar mockups de la pantalla de login', 'Crear wireframes y prototipos en Figma para el flujo de autenticación', 'COMPLETED', 'HIGH', NOW() + INTERVAL '2 days', 2, NOW(), NOW()),
  ('Revisar documentación de la API REST', 'Actualizar endpoints obsoletos y agregar ejemplos de respuesta', 'IN_PROGRESS', 'MEDIUM', NOW() + INTERVAL '5 days', 2, NOW(), NOW()),
  ('Configurar CI/CD en GitHub Actions', 'Pipeline de build, test y deploy automático para el repositorio principal', 'PENDING', 'HIGH', NOW() + INTERVAL '7 days', 2, NOW(), NOW()),
  ('Refactorizar módulo de autenticación', 'Separar lógica de negocio del controlador y mover a servicios', 'PENDING', 'MEDIUM', NOW() + INTERVAL '3 days', 2, NOW(), NOW()),
  ('Escribir tests unitarios para authController', 'Cubrir los casos de register, login, refresh y logout', 'IN_PROGRESS', 'HIGH', NOW() + INTERVAL '4 days', 2, NOW(), NOW()),
  ('Migrar base de datos a producción', 'Ejecutar migraciones de Prisma en el entorno productivo', 'PENDING', 'HIGH', NOW() + INTERVAL '1 day', 2, NOW(), NOW()),
  ('Optimizar consultas de la tabla Task', 'Agregar índices en userId y status para mejorar performance', 'PENDING', 'MEDIUM', NOW() + INTERVAL '10 days', 2, NOW(), NOW()),
  ('Implementar paginación en el listado de tareas', 'Agregar parámetros page y limit al endpoint GET /tasks', 'IN_PROGRESS', 'MEDIUM', NOW() + INTERVAL '6 days', 2, NOW(), NOW()),
  ('Configurar variables de entorno en producción', 'Subir secrets de JWT y DATABASE_URL al servidor', 'COMPLETED', 'HIGH', NOW() - INTERVAL '1 day', 2, NOW(), NOW()),
  ('Revisar vulnerabilidades con npm audit', 'Resolver las 3 vulnerabilidades de severidad alta detectadas', 'PENDING', 'HIGH', NOW() + INTERVAL '2 days', 2, NOW(), NOW()),
  ('Agregar validación de email en el registro', 'Verificar formato y dominio antes de crear el usuario', 'COMPLETED', 'LOW', NOW() - INTERVAL '3 days', 2, NOW(), NOW()),
  ('Crear endpoint de perfil de usuario', 'GET /users/me que retorne los datos del usuario autenticado', 'IN_PROGRESS', 'MEDIUM', NOW() + INTERVAL '5 days', 2, NOW(), NOW()),
  ('Integrar Nodemailer con Gmail', 'Configurar transporte SMTP y plantilla de bienvenida', 'PENDING', 'LOW', NOW() + INTERVAL '8 days', 2, NOW(), NOW()),
  ('Documentar endpoints con Swagger', 'Generar spec OpenAPI 3.0 para todos los endpoints del backend', 'PENDING', 'MEDIUM', NOW() + INTERVAL '12 days', 2, NOW(), NOW()),
  ('Implementar filtros en el listado de tareas', 'Filtrar por status, priority y dueDate desde query params', 'PENDING', 'MEDIUM', NOW() + INTERVAL '9 days', 2, NOW(), NOW()),
  ('Agregar middleware de logging', 'Registrar todas las requests con método, ruta y tiempo de respuesta', 'COMPLETED', 'LOW', NOW() - INTERVAL '5 days', 2, NOW(), NOW()),
  ('Configurar CORS para producción', 'Restringir origins permitidos al dominio del frontend en prod', 'COMPLETED', 'HIGH', NOW() - INTERVAL '2 days', 2, NOW(), NOW()),
  ('Revisar rate limiting en endpoints de auth', 'Ajustar ventana de tiempo y límite de intentos fallidos', 'IN_PROGRESS', 'HIGH', NOW() + INTERVAL '3 days', 2, NOW(), NOW()),
  ('Crear seed script para desarrollo', 'Generar usuarios y tareas de prueba con Prisma seed', 'PENDING', 'LOW', NOW() + INTERVAL '15 days', 2, NOW(), NOW()),
  ('Implementar soft delete para tareas', 'Agregar campo deletedAt y filtrar registros eliminados', 'PENDING', 'MEDIUM', NOW() + INTERVAL '11 days', 2, NOW(), NOW()),
  ('Actualizar dependencias del proyecto', 'Revisar changelog de cada paquete y actualizar a versiones estables', 'PENDING', 'LOW', NOW() + INTERVAL '20 days', 2, NOW(), NOW()),
  ('Optimizar tamaño del bundle del frontend', 'Configurar code splitting y lazy loading en React Router', 'IN_PROGRESS', 'MEDIUM', NOW() + INTERVAL '7 days', 2, NOW(), NOW()),
  ('Configurar Tailwind para modo oscuro', 'Implementar toggle de dark mode con persistencia en localStorage', 'PENDING', 'LOW', NOW() + INTERVAL '14 days', 2, NOW(), NOW()),
  ('Agregar toast notifications', 'Mostrar feedback visual al crear, editar y eliminar tareas', 'IN_PROGRESS', 'MEDIUM', NOW() + INTERVAL '4 days', 2, NOW(), NOW()),
  ('Revisar accesibilidad del formulario de login', 'Agregar aria-labels y navegación por teclado correcta', 'PENDING', 'LOW', NOW() + INTERVAL '18 days', 2, NOW(), NOW()),
  ('Implementar búsqueda de tareas', 'Campo de texto que filtre por título y descripción en tiempo real', 'PENDING', 'MEDIUM', NOW() + INTERVAL '10 days', 2, NOW(), NOW()),
  ('Conectar Redux con el módulo de tareas', 'Crear slice de tasks con acciones CRUD y thunks de Axios', 'IN_PROGRESS', 'HIGH', NOW() + INTERVAL '3 days', 2, NOW(), NOW()),
  ('Agregar skeleton loaders', 'Mostrar placeholders animados mientras cargan las tareas', 'PENDING', 'LOW', NOW() + INTERVAL '16 days', 2, NOW(), NOW()),
  ('Implementar drag and drop en el tablero', 'Permitir cambiar status arrastrando tarjetas entre columnas', 'PENDING', 'HIGH', NOW() + INTERVAL '25 days', 2, NOW(), NOW()),
  ('Crear componente de estadísticas', 'Gráfico de tareas por status y por prioridad en el dashboard', 'PENDING', 'MEDIUM', NOW() + INTERVAL '22 days', 2, NOW(), NOW()),
  ('Revisar flujo de refresh token', 'Asegurar que el interceptor de Axios renueve el token correctamente', 'COMPLETED', 'HIGH', NOW() - INTERVAL '4 days', 2, NOW(), NOW()),
  ('Agregar confirmación antes de eliminar tarea', 'Modal de confirmación con mensaje descriptivo antes del DELETE', 'IN_PROGRESS', 'MEDIUM', NOW() + INTERVAL '5 days', 2, NOW(), NOW()),
  ('Implementar ordenamiento de tareas', 'Permitir ordenar por fecha, prioridad y estado desde la UI', 'PENDING', 'MEDIUM', NOW() + INTERVAL '13 days', 2, NOW(), NOW()),
  ('Configurar ESLint y Prettier', 'Reglas compartidas entre frontend y backend con husky en pre-commit', 'COMPLETED', 'LOW', NOW() - INTERVAL '7 days', 2, NOW(), NOW()),
  ('Agregar campo de fecha límite al formulario', 'Date picker para asignar dueDate al crear o editar tarea', 'IN_PROGRESS', 'MEDIUM', NOW() + INTERVAL '6 days', 2, NOW(), NOW()),
  ('Implementar recuperación de contraseña', 'Enviar email con token temporal para resetear password', 'PENDING', 'HIGH', NOW() + INTERVAL '30 days', 2, NOW(), NOW()),
  ('Revisar manejo de errores en el frontend', 'Centralizar errores de Axios y mostrar mensajes al usuario', 'IN_PROGRESS', 'MEDIUM', NOW() + INTERVAL '4 days', 2, NOW(), NOW()),
  ('Crear página 404 personalizada', 'Redirigir rutas inexistentes a una página con mensaje amigable', 'COMPLETED', 'LOW', NOW() - INTERVAL '6 days', 2, NOW(), NOW()),
  ('Agregar protección de rutas privadas', 'Redirigir al login si el usuario no está autenticado', 'COMPLETED', 'HIGH', NOW() - INTERVAL '8 days', 2, NOW(), NOW()),
  ('Implementar edición inline de tareas', 'Editar título y descripción directamente desde la tarjeta', 'PENDING', 'MEDIUM', NOW() + INTERVAL '19 days', 2, NOW(), NOW()),
  ('Revisar política de cookies del refresh token', 'Asegurar atributos SameSite, HttpOnly y Secure en producción', 'PENDING', 'HIGH', NOW() + INTERVAL '8 days', 2, NOW(), NOW()),
  ('Crear tests de integración para tasks', 'Probar endpoints CRUD con supertest y base de datos de test', 'PENDING', 'HIGH', NOW() + INTERVAL '11 days', 2, NOW(), NOW()),
  ('Agregar campo de etiquetas a las tareas', 'Modelo Tag con relación many-to-many hacia Task', 'PENDING', 'LOW', NOW() + INTERVAL '35 days', 2, NOW(), NOW()),
  ('Optimizar re-renders en la lista de tareas', 'Usar React.memo y useCallback para evitar renders innecesarios', 'PENDING', 'MEDIUM', NOW() + INTERVAL '17 days', 2, NOW(), NOW()),
  ('Configurar Helmet para headers de seguridad', 'Revisar Content-Security-Policy y X-Frame-Options', 'COMPLETED', 'HIGH', NOW() - INTERVAL '9 days', 2, NOW(), NOW()),
  ('Implementar exportar tareas a CSV', 'Endpoint que devuelva las tareas del usuario en formato CSV', 'PENDING', 'LOW', NOW() + INTERVAL '40 days', 2, NOW(), NOW()),
  ('Agregar avatar de usuario', 'Upload de imagen con validación de tipo y tamaño máximo', 'PENDING', 'LOW', NOW() + INTERVAL '45 days', 2, NOW(), NOW()),
  ('Revisar performance con Lighthouse', 'Auditar el frontend y resolver issues de performance y SEO', 'PENDING', 'MEDIUM', NOW() + INTERVAL '28 days', 2, NOW(), NOW()),
  ('Configurar dominio y SSL en producción', 'Apuntar DNS y generar certificado con Let''s Encrypt', 'PENDING', 'HIGH', NOW() + INTERVAL '60 days', 2, NOW(), NOW()),
  ('Hacer deploy del backend en Railway', 'Subir la aplicación Node.js con variables de entorno configuradas', 'PENDING', 'HIGH', NOW() + INTERVAL '50 days', 2, NOW(), NOW());
