-- Bulk insert of fictional personal backlog tasks for the admin account.
-- Safe to run repeatedly: keyed by the unique "demoKey" column.

INSERT INTO "Task" ("title", "description", "status", "priority", "dueDate", "userId", "createdById", "demoKey", "createdAt", "updatedAt")
SELECT t.title, t.description, t.status::"TaskStatus", t.priority::"Priority", t.due_date, u.id, u.id, t.demo_key, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (VALUES
  ('Diseñar mockups de la pantalla de login', 'Crear wireframes y prototipos en Figma para el flujo de autenticación', 'COMPLETED', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '2 days', 'personal-task-001'),
  ('Revisar documentación de la API REST', 'Actualizar endpoints obsoletos y agregar ejemplos de respuesta', 'IN_PROGRESS', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '5 days', 'personal-task-002'),
  ('Configurar CI/CD en GitHub Actions', 'Pipeline de build, test y deploy automático para el repositorio principal', 'PENDING', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '7 days', 'personal-task-003'),
  ('Refactorizar módulo de autenticación', 'Separar lógica de negocio del controlador y mover a servicios', 'PENDING', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '3 days', 'personal-task-004'),
  ('Escribir tests unitarios para authController', 'Cubrir los casos de register, login, refresh y logout', 'IN_PROGRESS', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '4 days', 'personal-task-005'),
  ('Migrar base de datos a producción', 'Ejecutar migraciones de Prisma en el entorno productivo', 'PENDING', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '1 day', 'personal-task-006'),
  ('Optimizar consultas de la tabla Task', 'Agregar índices en userId y status para mejorar performance', 'PENDING', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '10 days', 'personal-task-007'),
  ('Implementar paginación en el listado de tareas', 'Agregar parámetros page y limit al endpoint GET /tasks', 'IN_PROGRESS', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '6 days', 'personal-task-008'),
  ('Configurar variables de entorno en producción', 'Subir secrets de JWT y DATABASE_URL al servidor', 'COMPLETED', 'HIGH', CURRENT_TIMESTAMP - INTERVAL '1 day', 'personal-task-009'),
  ('Revisar vulnerabilidades con npm audit', 'Resolver las 3 vulnerabilidades de severidad alta detectadas', 'PENDING', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '2 days', 'personal-task-010'),
  ('Agregar validación de email en el registro', 'Verificar formato y dominio antes de crear el usuario', 'COMPLETED', 'LOW', CURRENT_TIMESTAMP - INTERVAL '3 days', 'personal-task-011'),
  ('Crear endpoint de perfil de usuario', 'GET /users/me que retorne los datos del usuario autenticado', 'IN_PROGRESS', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '5 days', 'personal-task-012'),
  ('Integrar Nodemailer con Gmail', 'Configurar transporte SMTP y plantilla de bienvenida', 'PENDING', 'LOW', CURRENT_TIMESTAMP + INTERVAL '8 days', 'personal-task-013'),
  ('Documentar endpoints con Swagger', 'Generar spec OpenAPI 3.0 para todos los endpoints del backend', 'PENDING', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '12 days', 'personal-task-014'),
  ('Implementar filtros en el listado de tareas', 'Filtrar por status, priority y dueDate desde query params', 'PENDING', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '9 days', 'personal-task-015'),
  ('Agregar middleware de logging', 'Registrar todas las requests con método, ruta y tiempo de respuesta', 'COMPLETED', 'LOW', CURRENT_TIMESTAMP - INTERVAL '5 days', 'personal-task-016'),
  ('Configurar CORS para producción', 'Restringir origins permitidos al dominio del frontend en prod', 'COMPLETED', 'HIGH', CURRENT_TIMESTAMP - INTERVAL '2 days', 'personal-task-017'),
  ('Revisar rate limiting en endpoints de auth', 'Ajustar ventana de tiempo y límite de intentos fallidos', 'IN_PROGRESS', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '3 days', 'personal-task-018'),
  ('Crear seed script para desarrollo', 'Generar usuarios y tareas de prueba con Prisma seed', 'PENDING', 'LOW', CURRENT_TIMESTAMP + INTERVAL '15 days', 'personal-task-019'),
  ('Implementar soft delete para tareas', 'Agregar campo deletedAt y filtrar registros eliminados', 'PENDING', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '11 days', 'personal-task-020'),
  ('Actualizar dependencias del proyecto', 'Revisar changelog de cada paquete y actualizar a versiones estables', 'PENDING', 'LOW', CURRENT_TIMESTAMP + INTERVAL '20 days', 'personal-task-021'),
  ('Optimizar tamaño del bundle del frontend', 'Configurar code splitting y lazy loading en React Router', 'IN_PROGRESS', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '7 days', 'personal-task-022'),
  ('Configurar Tailwind para modo oscuro', 'Implementar toggle de dark mode con persistencia en localStorage', 'PENDING', 'LOW', CURRENT_TIMESTAMP + INTERVAL '14 days', 'personal-task-023'),
  ('Agregar toast notifications', 'Mostrar feedback visual al crear, editar y eliminar tareas', 'IN_PROGRESS', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '4 days', 'personal-task-024'),
  ('Revisar accesibilidad del formulario de login', 'Agregar aria-labels y navegación por teclado correcta', 'PENDING', 'LOW', CURRENT_TIMESTAMP + INTERVAL '18 days', 'personal-task-025'),
  ('Implementar búsqueda de tareas', 'Campo de texto que filtre por título y descripción en tiempo real', 'PENDING', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '10 days', 'personal-task-026'),
  ('Conectar Redux con el módulo de tareas', 'Crear slice de tasks con acciones CRUD y thunks de Axios', 'IN_PROGRESS', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '3 days', 'personal-task-027'),
  ('Agregar skeleton loaders', 'Mostrar placeholders animados mientras cargan las tareas', 'PENDING', 'LOW', CURRENT_TIMESTAMP + INTERVAL '16 days', 'personal-task-028'),
  ('Implementar drag and drop en el tablero', 'Permitir cambiar status arrastrando tarjetas entre columnas', 'PENDING', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '25 days', 'personal-task-029'),
  ('Crear componente de estadísticas', 'Gráfico de tareas por status y por prioridad en el dashboard', 'PENDING', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '22 days', 'personal-task-030'),
  ('Revisar flujo de refresh token', 'Asegurar que el interceptor de Axios renueve el token correctamente', 'COMPLETED', 'HIGH', CURRENT_TIMESTAMP - INTERVAL '4 days', 'personal-task-031'),
  ('Agregar confirmación antes de eliminar tarea', 'Modal de confirmación con mensaje descriptivo antes del DELETE', 'IN_PROGRESS', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '5 days', 'personal-task-032'),
  ('Implementar ordenamiento de tareas', 'Permitir ordenar por fecha, prioridad y estado desde la UI', 'PENDING', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '13 days', 'personal-task-033'),
  ('Configurar ESLint y Prettier', 'Reglas compartidas entre frontend y backend con husky en pre-commit', 'COMPLETED', 'LOW', CURRENT_TIMESTAMP - INTERVAL '7 days', 'personal-task-034'),
  ('Agregar campo de fecha límite al formulario', 'Date picker para asignar dueDate al crear o editar tarea', 'IN_PROGRESS', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '6 days', 'personal-task-035'),
  ('Implementar recuperación de contraseña', 'Enviar email con token temporal para resetear password', 'PENDING', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '30 days', 'personal-task-036'),
  ('Revisar manejo de errores en el frontend', 'Centralizar errores de Axios y mostrar mensajes al usuario', 'IN_PROGRESS', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '4 days', 'personal-task-037'),
  ('Crear página 404 personalizada', 'Redirigir rutas inexistentes a una página con mensaje amigable', 'COMPLETED', 'LOW', CURRENT_TIMESTAMP - INTERVAL '6 days', 'personal-task-038'),
  ('Agregar protección de rutas privadas', 'Redirigir al login si el usuario no está autenticado', 'COMPLETED', 'HIGH', CURRENT_TIMESTAMP - INTERVAL '8 days', 'personal-task-039'),
  ('Implementar edición inline de tareas', 'Editar título y descripción directamente desde la tarjeta', 'PENDING', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '19 days', 'personal-task-040'),
  ('Revisar política de cookies del refresh token', 'Asegurar atributos SameSite, HttpOnly y Secure en producción', 'PENDING', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '8 days', 'personal-task-041'),
  ('Crear tests de integración para tasks', 'Probar endpoints CRUD con supertest y base de datos de test', 'PENDING', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '11 days', 'personal-task-042'),
  ('Agregar campo de etiquetas a las tareas', 'Modelo Tag con relación many-to-many hacia Task', 'PENDING', 'LOW', CURRENT_TIMESTAMP + INTERVAL '35 days', 'personal-task-043'),
  ('Optimizar re-renders en la lista de tareas', 'Usar React.memo y useCallback para evitar renders innecesarios', 'PENDING', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '17 days', 'personal-task-044'),
  ('Configurar Helmet para headers de seguridad', 'Revisar Content-Security-Policy y X-Frame-Options', 'COMPLETED', 'HIGH', CURRENT_TIMESTAMP - INTERVAL '9 days', 'personal-task-045'),
  ('Implementar exportar tareas a CSV', 'Endpoint que devuelva las tareas del usuario en formato CSV', 'PENDING', 'LOW', CURRENT_TIMESTAMP + INTERVAL '40 days', 'personal-task-046'),
  ('Agregar avatar de usuario', 'Upload de imagen con validación de tipo y tamaño máximo', 'PENDING', 'LOW', CURRENT_TIMESTAMP + INTERVAL '45 days', 'personal-task-047'),
  ('Revisar performance con Lighthouse', 'Auditar el frontend y resolver issues de performance y SEO', 'PENDING', 'MEDIUM', CURRENT_TIMESTAMP + INTERVAL '28 days', 'personal-task-048'),
  ('Configurar dominio y SSL en producción', 'Apuntar DNS y generar certificado con Let''s Encrypt', 'PENDING', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '60 days', 'personal-task-049'),
  ('Hacer deploy del backend en Coolify', 'Subir la aplicación Node.js con variables de entorno configuradas', 'PENDING', 'HIGH', CURRENT_TIMESTAMP + INTERVAL '50 days', 'personal-task-050')
) AS t(title, description, status, priority, due_date, demo_key)
CROSS JOIN (SELECT id FROM "User" WHERE email = 'euclidesm195@gmail.com') AS u
ON CONFLICT ("demoKey") DO UPDATE SET
  "title" = EXCLUDED."title",
  "description" = EXCLUDED."description",
  "status" = EXCLUDED."status",
  "priority" = EXCLUDED."priority",
  "dueDate" = EXCLUDED."dueDate",
  "userId" = EXCLUDED."userId",
  "createdById" = EXCLUDED."createdById",
  "updatedAt" = CURRENT_TIMESTAMP;
